#ifndef PAPING_UTILS_PRINT_H
#define PAPING_UTILS_PRINT_H

#include "utils/standard.h"

#ifdef _WIN32
#define PRINT_COLOR_BLUE (FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY)
#define PRINT_COLOR_GREEN (FOREGROUND_GREEN | FOREGROUND_INTENSITY)
#define PRINT_COLOR_RED (FOREGROUND_RED | FOREGROUND_INTENSITY)
#define PRINT_COLOR_YELLOW (FOREGROUND_GREEN | FOREGROUND_RED | FOREGROUND_INTENSITY)
#else
#define PRINT_COLOR_BLUE 34
#define PRINT_COLOR_GREEN 32
#define PRINT_COLOR_RED 31
#define PRINT_COLOR_YELLOW 33
#endif

void print_formatted(int color, pcc_t data);
void print_set_color(int color);
void print_reset_color(void);

#endif /* PAPING_UTILS_PRINT_H */
